apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: vproapp
  name: vproapp
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: vproapp
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: vproapp
    spec:
      containers:
        - image: msabry/vproapp:v1
          name: vproapp
          ports:
            - containerPort: 8080
              protocol: TCP
              name: vproappdata
      restartPolicy: Always
