apiVersion: v1
kind: Service
metadata:
  name: hello
  namespace: helloworld
spec:
  selector:
    app: hello
  type: NodePort
  ports:
    - protocol: TCP
      nodePort: 31000
      port: 80
      targetPort: http